**load the original dataset**

In [1]:
# import the packages
import pandas as pd

In [2]:
# read the data by specifying the csv file
df = pd.read_csv('../../data/raw.csv')
# display the first few raws of the data
df.head()

,review,model,sentiment
0,The movie was a complete snoozefest. I regret...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was aw...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [3]:
# get the size of data
df.shape

(8236, 3)

In [4]:
#generate a statistical summary of dataframe
df.describe()

,review,model,sentiment
count,8236,8234,8234
unique,5678,6,3
top,This ad was pretty standard. The product was s...,Gemini-2.0-Flash-Lite,positive
freq,60,2853,3110

In [5]:
# get a concise su,,ary of DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8236 entries, 0 to 8235
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     8236 non-null   str
 1   model      8234 non-null   str
 2   sentiment  8234 non-null   str
dtypes: str(3)
memory usage: 193.2 KB

In [6]:
# check the missing value
df.isna().sum()

review       0
model        2
sentiment    2
dtype: int64

In [7]:
# Find rows with any missing value
rows_with_missing_data = df[df.isnull().any(axis=1)]

print("\nRows with missing values:")
print(rows_with_missing_data)

Rows with missing values:
                                                 review model sentiment
678             I'm furious!  This was a total rip-off.   NaN       NaN
7069  The clothes steamer removes wrinkles for quick...   NaN       NaN

In [8]:
# Check the total percentage of missing data in  model column
missing_percentage_model = df['model'].isnull().mean() * 100
print(f"Percentage missing in model: {missing_percentage_model}%")

# Check the total percentage of missing data in sentiment column
missing_percentage_senti = df['sentiment'].isnull().mean() * 100
print(f"Percentage missing in sentiment: {missing_percentage_senti}%")

Percentage missing in model: 0.024283632831471585%
Percentage missing in sentiment: 0.024283632831471585%

In [9]:

counts_senti = df['sentiment'].value_counts()
counts_model = df['model'].value_counts()
print(counts_senti)
print(counts_model)

sentiment
positive    3110
negative    2663
neutral     2461
Name: count, dtype: int64
model
Gemini-2.0-Flash-Lite    2853
GPT-5-mini               1661
GPT-4o-Mini              1507
Gemini-1.5-Flash         1194
Llama-3-8b-T              756
Mixtral-8x7b              263
Name: count, dtype: int64

In [10]:
df_clean = df.dropna(subset=['model','sentiment'],how='any')
df_clean.head()

,review,model,sentiment
0,The movie was a complete snoozefest. I regret...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was aw...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [11]:
df_clean.isna().sum()

review       0
model        0
sentiment    0
dtype: int64

In [12]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 8234 entries, 0 to 8235
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     8234 non-null   str
 1   model      8234 non-null   str
 2   sentiment  8234 non-null   str
dtypes: str(3)
memory usage: 257.3 KB

In [14]:
# save the processed data
df_clean.to_csv('../../data/processed.csv')