**load the original dataset**

In [12]:
# import the packages
import pandas as pd

In [13]:
# read the data by specifying the csv file
df = pd.read_csv('../../data/raw.csv')
# display the first few raws of the data
df.head()

,review,model,sentiment
0,The movie was a complete snoozefest. I regret...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was aw...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [14]:
# get the size of data
df.shape

(10147, 3)

In [15]:
#generate a statistical summary of dataframe
df.describe()

,review,model,sentiment
count,10147,10145,10145
unique,7584,9,3
top,This ad was pretty standard. The product was s...,Gemini-2.0-Flash-Lite,positive
freq,60,2853,3750

In [16]:
# get a concise su,,ary of DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10147 entries, 0 to 10146
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10147 non-null  str
 1   model      10145 non-null  str
 2   sentiment  10145 non-null  str
dtypes: str(3)
memory usage: 237.9 KB

In [17]:
# check the missing value
df.isna().sum()

review       0
model        2
sentiment    2
dtype: int64

In [18]:
# Find rows with any missing value
rows_with_missing_data = df[df.isnull().any(axis=1)]

print("\nRows with missing values:")
print(rows_with_missing_data)

Rows with missing values:
                                                 review model sentiment
678             I'm furious!  This was a total rip-off.   NaN       NaN
7069  The clothes steamer removes wrinkles for quick...   NaN       NaN

In [19]:
# Check the total percentage of missing data in  model column
missing_percentage_model = df['model'].isnull().mean() * 100
print(f"Percentage missing in model: {missing_percentage_model}%")

# Check the total percentage of missing data in sentiment column
missing_percentage_senti = df['sentiment'].isnull().mean() * 100
print(f"Percentage missing in sentiment: {missing_percentage_senti}%")

Percentage missing in model: 0.019710259189908347%
Percentage missing in sentiment: 0.019710259189908347%

In [20]:

counts_senti = df['sentiment'].value_counts()
counts_model = df['model'].value_counts()
print(counts_senti)
print(counts_model)

sentiment
positive    3750
negative    3311
neutral     3084
Name: count, dtype: int64
model
Gemini-2.0-Flash-Lite          2853
GPT-5-mini                     1661
GPT-4o-Mini                    1507
Gemini-1.5-Flash               1194
Grok-4.1-Fast-Non-Reasoning     831
Llama-3-8b-T                    756
Gemini-3-Flash                  657
GPT-5.2-Instant                 423
Mixtral-8x7b                    263
Name: count, dtype: int64

In [21]:
df_clean = df.dropna(subset=['model','sentiment'],how='any')
df_clean.head()

,review,model,sentiment
0,The movie was a complete snoozefest. I regret...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was aw...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [22]:
df_clean.isna().sum()

review       0
model        0
sentiment    0
dtype: int64

In [23]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 10145 entries, 0 to 10146
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10145 non-null  str
 1   model      10145 non-null  str
 2   sentiment  10145 non-null  str
dtypes: str(3)
memory usage: 317.0 KB

In [30]:

import re
# Option 1: Explicitly targeting NBSP (\u00A0) and standard whitespace
df_clean['review'] = df_clean['review'].str.replace(r'[\s\u00A0]+', ' ', regex=True).str.strip()

# Option 2: The "Burn it all down" approach (removes all non-standard whitespace)
# This replaces any sequence of whitespace-like characters with a single space
df_clean['review'] = df_clean['review'].str.replace(r'\s+', ' ', regex=True, flags=re.UNICODE).str.strip()

# Verification
df_verify = df_clean['review'].head(10).apply(lambda x: f"|{x}|")
#print(df_verify)
df_clean.head(5)

,review,model,sentiment
0,The movie was a complete snoozefest. I regrett...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was awf...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [31]:
df_clean.to_csv('../../data/processed.csv')
print("cleaned data saved successfully!")

cleaned data saved successfully!

In [118]:
df_clean.to_csv('../../data/processed.csv')

In [104]:
# Check a sample after cleaning
sample_text_clean = df['review'].iloc[0]
print([hex(ord(c)) for c in sample_text_clean if ord(c) > 0x7f])
# If the list above is empty, your "weird" unicode spaces are gone!

[]

In [105]:
# save the processed data
df.head()

,review,model,sentiment
0,The movie was a complete snoozefest. I regrett...,Gemini-1.5-Flash,negative
1,"Seriously, the worst venue I've ever been to. ...",Gemini-1.5-Flash,negative
2,"This event was so poorly organized, it was a j...",Gemini-1.5-Flash,negative
3,What a disaster of a movie! The acting was awf...,Gemini-1.5-Flash,negative
4,I wouldn't recommend this venue to my worst en...,Gemini-1.5-Flash,negative

In [86]:
sample_text = df['review'].iloc[0]
print([hex(ord(c)) for c in sample_text])

['0x54', '0x68', '0x65', '0x20', '0x6d', '0x6f', '0x76', '0x69', '0x65', '0x20', '0x77', '0x61', '0x73', '0x20', '0x61', '0x20', '0x63', '0x6f', '0x6d', '0x70', '0x6c', '0x65', '0x74', '0x65', '0x20', '0x73', '0x6e', '0x6f', '0x6f', '0x7a', '0x65', '0x66', '0x65', '0x73', '0x74', '0x2e', '0x20', '0x49', '0x20', '0x72', '0x65', '0x67', '0x72', '0x65', '0x74', '0x74', '0x65', '0x64', '0x20', '0x65', '0x76', '0x65', '0x72', '0x79', '0x20', '0x73', '0x65', '0x63', '0x6f', '0x6e', '0x64', '0x2e', '0x20', '0x54', '0x6f', '0x74', '0x61', '0x6c', '0x20', '0x77', '0x61', '0x73', '0x74', '0x65', '0x20', '0x6f', '0x66', '0x20', '0x6d', '0x6f', '0x6e', '0x65', '0x79', '0x2e']